import "@styles/globals.css";
import Navbar from "@components/Navbar";

export const metadata = {
  title: "D'Lux Organics",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
